### ISSUE TITLE
Can't start MicroDrop after updating from 2.14 to 2.15

### ISSUE THREAD

**Issue by ryanfobel** [sci-bots/microdrop#247]
## Steps to reproduce:

1. Install a fresh copy of [MicroDrop v2.14](https://github.com/sci-bots/microdrop/releases/tag/v2.14).
2. Set MicroDrop to check for updates: `Options\Update Automatically\check for updates, but ask before installing.`
3. Restart MicroDrop and agree to update to v2.15.

MicroDrop will fail to start. To determine the cause, start a `MicroDrop environment prompt` and launch the script `MicroDrop\Scripts>microdrop-profile-manager.exe` from your conda root.

This produced the output:

```python
(C:\Users\Wheeler\MicroDrop) C:\Users\Wheeler\MicroDrop\Scripts>microdrop-profile-manager.exe
Traceback (most recent call last):
  File "C:\Users\Wheeler\MicroDrop\Scripts\microdrop-profile-manager-script.py", line 3, in <module>
    import microdrop_launcher.bin.profile_launcher
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\microdrop_launcher\bin\profile_launcher.py", line 14, in <module>
    import pygtkhelpers.ui.dialogs as gd
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\pygtkhelpers\__init__.py", line 12, in <module>
    import schema
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\pygtkhelpers\schema.py", line 5, in <module>
    from flatland import Boolean, Enum, Float, Form, Integer, String
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\flatland\__init__.py", line 3, in <module>
    from flatland.schema import Array, Boolean, Compound, Constrained, Container,\
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\flatland\schema\__init__.py", line 2, in <module>
    from flatland.schema.base import (
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\flatland\schema\base.py", line 7, in <module>
    from flatland.signals import validator_validated
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\flatland\signals.py", line 1, in <module>
    from blinker import signal
ImportError: No module named blinker
```

When I run the command `conda list blinker` I got the following output:

```
# packages in environment at C:\Users\Wheeler\MicroDrop:
#
blinker                   1.4                        py_0    conda-forge
```

showing that `blinker=1.4` from the `conda-forge` channel is installed, but trying to run `import blinker` from a python shell fails.

Here's a copy of my conda environment [post update](https://github.com/sci-bots/microdrop/files/1612255/after-2.15-update-environment.yml.zip).

## Workaround

Install `blinker` from a `Microdrop environment prompt`:

```
conda install blinker
```

This installs `blinker=1.4` from the `wheeler-microfluidics` channel and MicroDrop now starts as expected.

**Comment by ryanfobel** [comment]
[Here's](https://github.com/sci-bots/microdrop/files/1612649/microdrop-v2.14-fresh-install-environment.yaml.zip) the exported conda environment after a fresh install of [MicroDrop v2.14](https://github.com/sci-bots/microdrop/releases/tag/v2.14).
