### ISSUE TITLE
bug(electrode-ctrl): actuation error after directional control past boundary

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop#258]
# Problem

While using the directional controls in the device UI, an exception is thrown in `set_electrode_states()` when triggering actuation in a direction where at least one electrode does not have a neighbour in the specified direction.

# Steps to reproduce

**TODO Needs to be determined**

# Cause

This is caused by duplicate entries in the electrode states series (i.e., the same electrode appears more than once in the index).

**Comment by cfobel** [comment]
Another occurrence:

```python
ERROR:dmf_device_ui.plugin:Error processing message from subscription socket.
Traceback (most recent call last):
  File "C:\Users\chris\Miniconda2-x86\envs\db-dev-copy\lib\site-packages\dmf_device_ui\plugin.py", line 74, in check_sockets
    data = decode_content_data(msg)
  File "C:\Users\chris\Documents\GitHub\zmq-plugin\zmq_plugin\schema.py", line 243, in decode_content_data
    raise RuntimeError(error)
RuntimeError: Traceback (most recent call last):
  File "C:\Users\chris\Documents\GitHub\zmq-plugin\zmq_plugin\plugin.py", line 342, in _process__execute_request
    data = func(request)
  File "microdrop\core_plugins\electrode_controller_plugin\__init__.py", line 323, in on_execute__get_channel_states
    return self.get_channel_states()
  File "microdrop\core_plugins\electrode_controller_plugin\__init__.py", line 168, in get_channel_states
    result = self.get_state(self.electrode_states)
  File "microdrop\core_plugins\electrode_controller_plugin\__init__.py", line 146, in get_state
    index=electrode_channels)
  File "C:\Users\chris\Miniconda2-x86\envs\db-dev-copy\lib\site-packages\pandas\core\series.py", line 266, in __init__
    data = SingleBlockManager(data, index, fastpath=True)
  File "C:\Users\chris\Miniconda2-x86\envs\db-dev-copy\lib\site-packages\pandas\core\internals.py", line 4402, in __init__
    fastpath=True)
  File "C:\Users\chris\Miniconda2-x86\envs\db-dev-copy\lib\site-packages\pandas\core\internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "C:\Users\chris\Miniconda2-x86\envs\db-dev-copy\lib\site-packages\pandas\core\internals.py", line 120, in __init__
    len(self.mgr_locs)))
ValueError: Wrong number of items passed 6, placement implies 4
```

Trying to use "up" direction control here:

![image](https://user-images.githubusercontent.com/823355/44814808-c0f77400-abab-11e8-8928-6b8b3f24627e.png)
